# Specifies the model file for training. Accepts a path to a .pt pretrained model.
# Type: str
# Allowed values: Any valid file path
model: yolo26x.pt

# Path to the dataset configuration file (e.g., coco8.yaml). Contains dataset-specific parameters.
# Type: str
# Allowed values: Any valid file path
data: /home/simone/myprojects/ClearSAR/ClearSAR/yolo_dataset/dataset.yaml

# Total number of training epochs. Each epoch represents a full pass over the entire dataset.
# Type: int
# Default: 100
# Allowed values: >= 1
epochs: 300

# Maximum training time in hours. Overrides the epochs argument if set.
# Type: float
# Default: null
# Allowed values: > 0 or null
time: null

# Number of epochs to wait without improvement in validation metrics before early stopping.
# Type: int
# Default: 100
# Allowed values: >= 1
patience: 30

# Batch size. Can be set as an integer, auto mode for GPU utilization, or auto with specified fraction.
# Type: int/float
# Default: 16
# Allowed values: int >= 1 or int == -1 or float in (0.0, 1.0] 
batch: 16

# Target image size for training. All images are resized to this dimension.
# Type: int or list[int]
# Default: 640
# Allowed values: >= 32
imgsz: 640

# Enables saving of training checkpoints and final model weights.
# Type: bool
# Default: true
save: true

# Frequency of saving model checkpoints, specified in epochs. -1 disables this feature.
# Type: int
# Default: -1
# Allowed values: [1, epochs] or -1
save_period: 25

# Enables caching of dataset images in memory (true/ram), on disk (disk), or disables it (false).
# Type: bool or str
# Default: false
cache: false

# Specifies the computational device(s) for training: GPU, CPU, or MPS.
# Type: int, str, or list
# Allowed values: int >=0 ,list[int] >=0 , str in  ['cpu', 'mps']
device: 0

# Number of worker threads for data loading.
# Type: int
# Default: 8
# Allowed values: >= -1
workers: 8

# Name of the project directory where training outputs are saved.
# Type: str
# Allowed values: Any valid string
project: experiments

# Name of the training run. Used for creating a subdirectory within the project folder.
# Type: str
# Allowed values: Any valid string
name: yolo26x_run

# If true, allows overwriting of an existing project/name directory.
# Type: bool
# Default: false
exist_ok: true

# Determines whether to start training from a pretrained model.
# Type: bool
# Default: true
pretrained: true

# Choice of optimizer for training.
# Type: str
# Default: 'auto'
# Allowed values: 'SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp', or 'auto'
optimizer: auto

# Sets the random seed for training, ensuring reproducibility.
# Type: int
# Default: 0
# Allowed values: >=0
seed: 0

# Forces deterministic algorithm use for reproducibility.
# Type: bool
# Default: true
deterministic: true

# Treats all classes in multi-class datasets as a single class during training.
# Type: bool
# Default: false
single_cls: false

# Specifies a list of class IDs to train on.
# Type: list[int]
# Allowed values: Any valid list of integers or null
classes: null

# Enables rectangular training for minimal padding.
# Type: bool
# Default: false
rect: false

# Utilizes a cosine learning rate scheduler.
# Type: bool
# Default: false
cos_lr: true

# Disables mosaic augmentation in the last N epochs.
# Type: int
# Default: 10
# Allowed values: >= 0
close_mosaic: 10

# Resumes training from the last saved checkpoint.
# Type: bool
# Default: false
resume: false

# Enables Automatic Mixed Precision (AMP) training.
# Type: bool
# Default: true
amp: true

# Specifies the fraction of the dataset to use for training.
# Type: float
# Default: 1.0
# Allowed values: (0.0, 1.0]
fraction: 1.0

# Enables profiling of ONNX and TensorRT speeds during training.
# Type: bool
# Default: false
profile: false

# Freezes the first N layers or specified layers by index.
# Type: int
# Allowed values: >= 1 or null
freeze: null

# Initial learning rate.
# Type: float
# Default: 0.01
# Allowed values: >0
lr0: 0.001

# Final learning rate as a fraction of the initial rate.
# Type: float
# Default: 0.01
# Allowed values: >0
lrf: 0.01

# Momentum factor for SGD or beta1 for Adam optimizers.
# Type: float
# Default: 0.937
# Allowed values: [0.0, 1.0)
momentum: 0.937

# L2 regularization term.
# Type: float
# Default: 0.0005
# Allowed values: >=0
weight_decay: 0.0005

# Number of epochs for learning rate warmup.
# Type: int
# Default: 3
# Allowed values: >= 0
warmup_epochs: 20

# Initial momentum for the warmup phase.
# Type: float
# Default: 0.8
# Allowed values: [0.0, 1.0)
warmup_momentum: 0.8

# Learning rate for bias parameters during warmup.
# Type: float
# Default: 0.1
# Allowed values: > 0
warmup_bias_lr: 0.1

# Weight of the box loss component in the loss function.
# Type: float
# Default: 7.5
# Allowed values: > 0
box: 7.5

# Weight of the classification loss in the total loss function.
# Type: float
# Default: 0.5
# Allowed values: > 0
cls: 0.5

# Weight of the distribution focal loss.
# Type: float
# Default: 1.5
# Allowed values: > 0
dfl: 1.5

# Weight of the pose loss for pose estimation.
# Type: float
# Default: 12.0
# Allowed values: > 0
pose: 12.0

# Weight of the keypoint objectness loss in pose estimation models.
# Type: float
# Default: 2.0
# Allowed values: > 0
kobj: 2.0

# Nominal batch size for normalization of loss.
# Type: int
# Default: 64
# Allowed values: > 0
nbs: 64

# Determines whether object masks should be merged for training.
# Type: bool
# Default: true
overlap_mask: true

# Downsample ratio for segmentation masks.
# Type: int
# Default: 4
mask_ratio: 4

# Dropout rate for regularization in classification tasks.
# Type: float
# Default: 0.0
# Allowed values: [0.0. 1.0)
dropout: 0.1

# Enables validation during training.
# Type: bool
# Default: true
val: true

# Generates and saves plots of training and validation metrics.
# Type: bool
# Default: false
plots: true

# Data augmentation arguments follow.
# Adjusts the hue of the image by a fraction of the color wheel.
# Type: float
# Default: 0.015
# Range: [0.0 - 1.0]
hsv_h: 0.0

# Alters the saturation of the image.
# Type: float
# Default: 0.7
# Range: [0.0 - 1.0]
hsv_s: 0.5

# Modifies the value (brightness) of the image.
# Type: float
# Default: 0.4
# Range: [0.0 - 1.0]
hsv_v: 0.5

# Rotates the image randomly within the specified degree range.
# Type: float
# Default: 0.0
# Range: [-180 to 180]
degrees: 45.0

# Translates the image horizontally and vertically.
# Type: float
# Default: 0.1
# Range: [0.0 - 1.0]
translate: 0.2

# Scales the image by a gain factor.
# Type: float
# Default: 0.5
# Range: >= 0.0
scale: 0.5

# Shears the image by a specified degree.
# Type: float
# Default: 0.0
# Range: [-180 to 180]
shear: 0.0

# Applies a random perspective transformation.
# Type: float
# Default: 0.0
# Range: [0.0 - 0.001]
perspective: 0.0

# Flips the image upside down.
# Type: float
# Default: 0.0
# Range: [0.0 - 1.0]
flipud: 0.25

# Flips the image left to right.
# Type: float
# Default: 0.5
# Range: [0.0 - 1.0]
fliplr: 0.5

# Flips the image channels from RGB to BGR.
# Type: float
# Default: 0.0
# Range: [0.0 - 1.0]
bgr: 0.0

# Combines four training images into one.
# Type: float
# Default: 1.0
# Range: [0.0 - 1.0]
mosaic: 0.75

# Blends two images and their labels.
# Type: float
# Default: 0.0
# Range: [0.0 - 1.0]
mixup: 0.0

# Copies and pastes objects across images.
# Type: float
# Default: 0.0
# Range: [0.0 - 1.0]
copy_paste: 0.0

# Copy-Paste augmentation method selection.
# Type: str
# Default: 'flip'
# Allowed values: ['flip', 'mixup']
copy_paste_mode: 'flip'

# Automatically applies a predefined augmentation policy.
# Type: str
# Default: 'randaugment'
# Allowed values: ['randaugment', 'autoaugment', 'augmix']
auto_augment: 'randaugment'

# Randomly erases a portion of the image.
# Type: float
# Default: 0.4
# Range: [0.0 - 0.9]
erasing: 0.0

# Crops the classification image to a fraction of its size.
# Type: float
# Default: 1.0
# Range: [0.1 - 1.0]
crop_fraction: 1.0